---
- name: install nginx
  yum: name=nginx state=present

- template: src={{ item }}.j2 dest=/etc/nginx/{{ item }}
  with_items:
    - nginx.conf
    - conf.d/virtual.conf
  notify: reload nginx

- file:
    path: /usr/share/nginx/www
    state: directory

- name: start and enabled nginx
  service: name=nginx state=started enabled=yes
