---
- name: install nginx
  yum: name=nginx state=present

- template: src={{ item }}.j2 dest=/etc/nginx/{{ item }}
  with_items:
    - nginx.conf
    - conf.d/virtual.conf
  notify: reload nginx

- name: start and enabled nginx
  service: name=nginx state=started enabled=yes
