# -*- mode: ruby -*-
# vi: set ft=ruby :
$num_instances = 2
Vagrant.configure(2) do |config|
  config.vm.box = "centos6.5"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box"
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end
  config.vm.provider :virtualbox do |v|
    v.check_guest_additions = false
    v.functional_vboxsf     = false
  end
  config.vm.boot_timeout = 300
  config.vm.synced_folder ".", "/vagrant", disabled: true
  (1..$num_instances).each do |i|
    config.vm.define vm_name = "web%01d" % i do |host|
      host.vm.hostname = vm_name
      ip = "192.168.33.#{i+100}"
      host.vm.network :private_network, ip: ip
      host.vm.provider "virtualbox" do | vb |
        vb.gui = false
        vb.customize ["modifyvm", :id, "--cpus", 1]
        vb.customize ["modifyvm", :id, "--memory", "1024"]
      end
    end
  end
end
